# Generated by Django 2.1.5 on 2019-02-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languages',
            old_name='langauge',
            new_name='language',
        ),
    ]
