# Generated by Django 2.1.7 on 2019-03-18 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190211_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wcuclasses',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='wcuclasses',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Languages',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.DeleteModel(
            name='WCUClasses',
        ),
    ]
